name: inventox-clean
services:
- name: web
  source_dir: /
  github:
    repo: SEDLopes/inventox-clean
    branch: main
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  envs:
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${inventox-db.HOSTNAME}
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${inventox-db.DATABASE}
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: ${inventox-db.USERNAME}
  - key: DB_PASS
    scope: RUN_AND_BUILD_TIME
    value: ${inventox-db.PASSWORD}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${inventox-db.PORT}
  - key: DEBUG_MODE
    value: "false"
  - key: ENVIRONMENT
    value: "production"

databases:
- name: inventox-db
  engine: MYSQL
  version: "8"
  size: db-s-dev-database
