name: inventox-app
services:
- name: web
  source_dir: /
  github:
    repo: SEDLopes/inventox-app
    branch: main
  run_command: apache2-foreground
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile
  http_port: 80
  routes:
  - path: /
  envs:
  - key: DB_HOST
    value: ${inventox-db.HOSTNAME}
  - key: DB_NAME
    value: ${inventox-db.DATABASE}
  - key: DB_USER
    value: ${inventox-db.USERNAME}
  - key: DB_PASS
    value: ${inventox-db.PASSWORD}
  - key: DB_PORT
    value: ${inventox-db.PORT}
  - key: DEBUG_MODE
    value: "false"
  - key: ENVIRONMENT
    value: "production"

databases:
- name: inventox-db
  engine: MYSQL
  version: "8"
  size: db-s-dev-database