name: inventox
services:
  - name: inventox-web
    source_dir: /
    github:
      repo: SEDLopes/inventox-app
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DB_HOST
        scope: RUN_TIME
        value: ${db-mysql-fra1-70732.HOSTNAME}
      - key: DB_NAME
        scope: RUN_TIME
        value: ${db-mysql-fra1-70732.DATABASE}
      - key: DB_USER
        scope: RUN_TIME
        value: ${db-mysql-fra1-70732.USERNAME}
      - key: DB_PASS
        scope: RUN_TIME
        value: ${db-mysql-fra1-70732.PASSWORD}
      - key: DB_PORT
        scope: RUN_TIME
        value: ${db-mysql-fra1-70732.PORT}
databases:
  - name: db-mysql-fra1-70732
    engine: MYSQL
    version: "8"
    production: false